const listaMenus = [
    { id:"0001",
    nombre: "Milanesas con puré",
pais: "Argentina",
continente:"Latinoamerica",
img:"https://caraotadigital.org/wp-content/uploads/2020/08/Lo-mejor-de-dos-milanesas-de-pollo-rellenas-de-pure-de-papa-Video.jpg",
precio:"350",
estado:true,
    },
    {
        id:"0002",
        nombre: "Sushi",
    pais: "Japon",
    continente:"Asia",
    img:"https://caraotadigital.org/wp-content/uploads/2020/08/Lo-mejor-de-dos-milanesas-de-pollo-rellenas-de-pure-de-papa-Video.jpg",
    precio:"350",
    estado:true,
        },
        {
            id:"0003",
            nombre: "Paella Valenciana",
        pais: "España",
        continente:"Europa",
        img:"https://caraotadigital.org/wp-content/uploads/2020/08/Lo-mejor-de-dos-milanesas-de-pollo-rellenas-de-pure-de-papa-Video.jpg",
        precio:"350",
        estado:true,
            },
            {
                id:"0004",
                nombre: "Pollo Nyembwe",
            pais: "Gabón",
            continente:"Africa",
            img:"https://caraotadigital.org/wp-content/uploads/2020/08/Lo-mejor-de-dos-milanesas-de-pollo-rellenas-de-pure-de-papa-Video.jpg",
            precio:"350",
            estado:true,
                },
                {
                    id:"0005",
                    nombre: "Hangi",
                pais: "Nueva Zelanda",
                continente:"Oceania",
                img:"https://caraotadigital.org/wp-content/uploads/2020/08/Lo-mejor-de-dos-milanesas-de-pollo-rellenas-de-pure-de-papa-Video.jpg",
                precio:"350",
                estado:true,
                    },
                    {
                        id:"0006",
                        nombre: "Fiddleheads",
                    pais: "Canadá",
                    continente:"America del Norte",
                    img:"https://caraotadigital.org/wp-content/uploads/2020/08/Lo-mejor-de-dos-milanesas-de-pollo-rellenas-de-pure-de-papa-Video.jpg",
                    precio:"350",
                    estado:true,
                        },];

export default listaMenus;
